#-----------------------------------------------
# GitHub Action Part-1 - Basics
#
# Copyleft (c) by Maksim Zhelnov 2022
#-----------------------------------------------
name: My-GitHubActions-Basics
env: 
  APPLICATION_NAME    : "MyFlask"
  DEPLOY_PACKAGE_NAME : "flask-deploy-ver-${{ github.sha }}"

on:
  push:
    branches:
      - master

jobs:
  my_testing:
    runs-on: ubuntu-latest
    
    steps:
    - name: Print Hello Message
      run : echo "Hello Word from Testing job"

    - name: Execure few commands
      run : |
        echo "Hello Message1"
        echo "Hello Message2"
        echo "Aplication name: ${{ env.APPLICATION_NAME }}"
        
    - name: Git clone my repo
      uses: actions/checkout@v2.5.0
    
    - name: List current folder
      run : ls -la
      
    
    
  my_deploy:
    runs-on: ubuntu-latest
    needs: [my_testing]
    env:
      VAR1: "This is Job lavel Varible1"
      VAR2: "This is Job lavel Varible2"
      
    steps:
      - name: Print Hello Message
        run : echo "Hello Word from Deploy job"
      - name: Print env vars
        run : 
          echo "Var1 = ${{ env.VAR1 }}"
          echo "Var2 - ${{ env.VAR2 }}"
          echo "Var3 = $LOCAL_VAR"       
        env:
          LOCAL_VAR: "This is Super local Enviroment variable"
          
          
      - name: Printing Deployment pakcege
        run : echo "Deploy pakcage name is ${{ env.DEPLOY_PACKAGE_NAME }}" 

      - name: Lets test some packages iof the are here 1
        run : aws --version
       
      - name: Lets test some packages iof the are here 2
        run : zip --version
       
