#-----------------------------------------------
# GitHub Action Part-1 - Basics
#
# Copyleft (c) by Maksim Zhelnov 2022
#-----------------------------------------------
name: My-GitHubActions-Basics
env: 
  APPLICATION_NAME    : "MyFlask"
  DEPLOY_PACKAGE_NAME : "flask-deploy-ver-${{ github.sha }}"

on:
  push:
    branches:
      - master

jobs:
  my_testing:
    runs-on: ubuntu-latest
    
    steps:
    - name: Print Hello Message
      run : echo "Hello Word from Testing job"

    - name: Execure few commands
      run : |
        echo "Hello Message1"
        echo "Hello Message2"
        echo "Aplication name: ${{ env.APPLICATION_NAME }}"
    
    - name: List current folder
      run : ls -la
      
    - name: Git clone my repo
      uses: actions/chekout@v3
    
  my_deploy:
    runs-on: ubuntu-latest
    needs: [my_testing]

    steps:
      - name: Print Hello Message
        run : echo "Hello Word from Deploy job"
        
      - name: Printing Deployment pakcege
        run : echo "Deploy pakcage name is ${{ env.DEPLOY_PACKAGE_NAME }}" 

      - name: Lets test some packages iof the are here 1
        run : aws --version
       
      - name: Lets test some packages iof the are here 2
        run : zip 
       
